#!/bin/bash
set -ex

PREFIX=~/.installations

# Build kokkos 
cd ~
mkdir .installations 
mkdir .work
cd .work

git clone https://github.com/kokkos/kokkos.git
mkdir kokkos/build
cd kokkos/build
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON \
          -DBUILD_SHARED_LIBS=ON    \
          -DKokkos_CXX_STANDARD=17  \
../
make install

# Install MParT
cd ~/.work
git clone -b main --single-branch https://github.com/MeasureTransport/MParT.git
mkdir MParT/build
cd MParT/build 
cmake -DMPART_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX -DPYTHON_EXECUTABLE=`which python` ../
make install 

# Clean up build folders
cd ~
rm -rf ~/.work

# Generate jupyter notebooks from python scripts
jupyter lab build

cd ~/examples/python

export PYTHONPATH=$PYTHONPATH:$PREFIX/python

jupytext --set-formats ipynb,py MonotoneLeastSquares.py
jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute MonotoneLeastSquares.ipynb

jupytext --set-formats ipynb,py StochasticVolatility.py
jupyter nbconvert --ExecutePreprocessor.timeout=3600 --to notebook --execute StochasticVolatility.ipynb

cd ~/examples/cpp 
python ~/.binder/CppToNotebook.py MonotoneLeastSquares/MonotoneLeastSquares.cpp MonotoneLeastSquares/MonotoneLeastSquares.ipynb
jupyter nbconvert --ExecutePreprocessor.timeout=3600 --to notebook --execute MonotoneLeastSquares/MonotoneLeastSquares.ipynb
